PRAGMA foreign_keys=OFF;
INSERT INTO quotes VALUES('1',' ø\_(_)_/ø');
INSERT INTO quotes VALUES('2','Get that shit outta my master.');
INSERT INTO quotes VALUES('3','#GrammarNazi');
INSERT INTO quotes VALUES('4','$(init 0)');
INSERT INTO quotes VALUES('5','$(rm -rvf .)');
INSERT INTO quotes VALUES('6','(\ /)<br/>(O.o)<br/>(&gt; &lt;) Bunny approves these changes.');
INSERT INTO quotes VALUES('7','(c) Microsoft 1988');
INSERT INTO quotes VALUES('8','#NAME?');
INSERT INTO quotes VALUES('9','-m \''So I hear you like commits ...\''');
INSERT INTO quotes VALUES('10','.');
INSERT INTO quotes VALUES('11','...');
INSERT INTO quotes VALUES('12','/sigh');
INSERT INTO quotes VALUES('13','50/50');
INSERT INTO quotes VALUES('14','640K ought to be enough for anybody');
INSERT INTO quotes VALUES('15','8==========D');
INSERT INTO quotes VALUES('16',':(:(');
INSERT INTO quotes VALUES('17',':q!');
INSERT INTO quotes VALUES('18','??! what the ...');
INSERT INTO quotes VALUES('19','[FIX] asdf');
INSERT INTO quotes VALUES('20','A fix I believe, not like I tested or anything');
INSERT INTO quotes VALUES('21','A full commitment''s what I''m thinking of');
INSERT INTO quotes VALUES('22','A long time ago, in a galaxy far far away...');
INSERT INTO quotes VALUES('23','A tale of Dragons, Heroes and Legends...');
INSERT INTO quotes VALUES('24','ALL SORTS OF THINGS');
INSERT INTO quotes VALUES('25','Abandon all hope, ye who enter here.');
INSERT INTO quotes VALUES('26','Actual final build before release');
INSERT INTO quotes VALUES('27','Add Sandbox');
INSERT INTO quotes VALUES('28','Added a banner to the default admin page. Please have mercy on me =(');
INSERT INTO quotes VALUES('29','Added another dependency');
INSERT INTO quotes VALUES('30','Added missing file in previous commit');
INSERT INTO quotes VALUES('31','Added some NullPointerExceptions - Happy easter, you bastards! :D');
INSERT INTO quotes VALUES('32','Added translation.');
INSERT INTO quotes VALUES('33','All your codebase are belong to us.');
INSERT INTO quotes VALUES('34','And a commit that I don''t know the reason of...');
INSERT INTO quotes VALUES('35','And if you ask me how I''m feeling');
INSERT INTO quotes VALUES('36','And if thou''rt unwilling, then force I''ll employ');
INSERT INTO quotes VALUES('37','Another bug bites the dust');
INSERT INTO quotes VALUES('38','Another commit to keep my CAN streak going.');
INSERT INTO quotes VALUES('39','Apparently works-for-me is a crappy excuse.');
INSERT INTO quotes VALUES('40','Argh! About to give up :(');
INSERT INTO quotes VALUES('41','Arrrrgggg');
INSERT INTO quotes VALUES('42','At times like this I wish I was a Garbage Man.');
INSERT INTO quotes VALUES('43','Automate Accounting');
INSERT INTO quotes VALUES('44','Batman! (this commit has no parents)');
INSERT INTO quotes VALUES('45','Become a programmer, they said. It''ll be fun, they said.');
INSERT INTO quotes VALUES('46','Best commit ever');
INSERT INTO quotes VALUES('47','Bit Bucket is down. What should I do now?');
INSERT INTO quotes VALUES('48','Blaming regex.');
INSERT INTO quotes VALUES('49','By works, I meant ''doesnt work''.  Works now..');
INSERT INTO quotes VALUES('50','COMMIT ALL THE FILES!');
INSERT INTO quotes VALUES('51','Can someone review this commit, please ?');
INSERT INTO quotes VALUES('52','Check next commit for message.');
INSERT INTO quotes VALUES('53','Chuck Norris Emailed Me This Patch... I''m Not Going To Question It');
INSERT INTO quotes VALUES('54','Code was clean until manager requested to fuck it up');
INSERT INTO quotes VALUES('55','Commit committed');
INSERT INTO quotes VALUES('56','Commit committed....');
INSERT INTO quotes VALUES('57','Committed some changes');
INSERT INTO quotes VALUES('58','Committing fixes in the dark, seriously, who killed my power!?');
INSERT INTO quotes VALUES('59','Committing in accordance with the prophecy.');
INSERT INTO quotes VALUES('60','Completed with no bugs...');
INSERT INTO quotes VALUES('61','Continued development...');
INSERT INTO quotes VALUES('62','Copy pasta fail. still had a instead of a');
INSERT INTO quotes VALUES('63','Copy-paste to fix previous copy-paste');
INSERT INTO quotes VALUES('64','Corrected mistakes');
INSERT INTO quotes VALUES('65','Crap. Tonight is raid night and I am already late.');
INSERT INTO quotes VALUES('66','DEAL WITH IT');
INSERT INTO quotes VALUES('67','DNS_PROBE_FINISHED_NXDOMAIN');
INSERT INTO quotes VALUES('68','Deleted API file');
INSERT INTO quotes VALUES('69','Derp');
INSERT INTO quotes VALUES('70','Derp search/replace fuckup');
INSERT INTO quotes VALUES('71','Derp, asset redirection in dev mode');
INSERT INTO quotes VALUES('72','Derp. Fix missing constant post rename');
INSERT INTO quotes VALUES('73','Derpy hooves');
INSERT INTO quotes VALUES('74','Do things better, faster, stronger');
INSERT INTO quotes VALUES('75','Does anyone read this? I''ll be at the coffee shop accross the street.');
INSERT INTO quotes VALUES('76','Does not work.');
INSERT INTO quotes VALUES('77','Does this work');
INSERT INTO quotes VALUES('78','Don''t Ask Me, I Have No Idea Why This Works Either');
INSERT INTO quotes VALUES('79','Don''t push this commit');
INSERT INTO quotes VALUES('80','Don''t tell me you''re too blind to see');
INSERT INTO quotes VALUES('81','Done, to whoever merges this, good luck.');
INSERT INTO quotes VALUES('82','DonÕt even try to refactor it.');
INSERT INTO quotes VALUES('83','DonÕt mess with Voodoo');
INSERT INTO quotes VALUES('84','Duh');
INSERT INTO quotes VALUES('85','Easteregg');
INSERT INTO quotes VALUES('86','Either Hot Shit or Total Bollocks');
INSERT INTO quotes VALUES('87','Errare humanum est.');
INSERT INTO quotes VALUES('88','FONDLED THE CODE');
INSERT INTO quotes VALUES('89','FOR REAL.');
INSERT INTO quotes VALUES('90','FUCKING XUPPERNAMEX');
INSERT INTO quotes VALUES('91','Feed. You. Stuff. No time.');
INSERT INTO quotes VALUES('92','Final commit, ready for tagging');
INSERT INTO quotes VALUES('93','Fingers crossed!');
INSERT INTO quotes VALUES('94','Finished fondling.');
INSERT INTO quotes VALUES('95','First Blood');
INSERT INTO quotes VALUES('96','Fix PC Load Letter Error');
INSERT INTO quotes VALUES('97','Fix all errors, all errors on the WORLD!!!!');
INSERT INTO quotes VALUES('98','Fix edge, single client, error case');
INSERT INTO quotes VALUES('99','Fix hard-coded [object Object] string (thanks!)');
INSERT INTO quotes VALUES('100','Fix my stupidness');
INSERT INTO quotes VALUES('101','Fix the fixes');
INSERT INTO quotes VALUES('102','Fixed Bug');
INSERT INTO quotes VALUES('103','Fixed a bug cause XNAMEX said to');
INSERT INTO quotes VALUES('104','Fixed a bug in NoteLineCount... not seriously...');
INSERT INTO quotes VALUES('105','Fixed a little bug...');
INSERT INTO quotes VALUES('106','Fixed compilation errors');
INSERT INTO quotes VALUES('107','Fixed errors');
INSERT INTO quotes VALUES('108','Fixed everything.');
INSERT INTO quotes VALUES('109','Fixed mispeling');
INSERT INTO quotes VALUES('110','Fixed so the code compiles');
INSERT INTO quotes VALUES('111','Fixed some shit');
INSERT INTO quotes VALUES('112','Fixed the build.');
INSERT INTO quotes VALUES('113','Fixed the fuck out of #XNUMX!');
INSERT INTO quotes VALUES('114','Fixed unnecessary bug.');
INSERT INTO quotes VALUES('115','Fixed what was broken.');
INSERT INTO quotes VALUES('116','Fixing XNAMEX''s bug.');
INSERT INTO quotes VALUES('117','Fixing XNAMEX''s bugs.');
INSERT INTO quotes VALUES('118','For great justice.');
INSERT INTO quotes VALUES('119','For real, this time.');
INSERT INTO quotes VALUES('120','For the sake of my sanity, just ignore this...');
INSERT INTO quotes VALUES('121','For the statistics only');
INSERT INTO quotes VALUES('122','Friday 5pm');
INSERT INTO quotes VALUES('123','Fuck it, YOLO!');
INSERT INTO quotes VALUES('124','Fucking egotistical bastard. adds expandtab to vimrc');
INSERT INTO quotes VALUES('125','Fucking submodule bull shit');
INSERT INTO quotes VALUES('126','Fucking templates.');
INSERT INTO quotes VALUES('127','Future self, please forgive me and don''t hit me with the baseball bat again!');
INSERT INTO quotes VALUES('128','GIT :/');
INSERT INTO quotes VALUES('129','General commit (no IDs open) - Modifications for bad implementations');
INSERT INTO quotes VALUES('130','Git wants e to commit, I want to sleep. Take me sweet void.');
INSERT INTO quotes VALUES('131','Give me a break, it''s 2am.  But it works now.');
INSERT INTO quotes VALUES('132','Glue. Match sticks. Paper. Build script!');
INSERT INTO quotes VALUES('133','Gotta make you understand');
INSERT INTO quotes VALUES('134','Gross hack because XNAMEX doesn''t know how to code');
INSERT INTO quotes VALUES('135','Handled a particular error.');
INSERT INTO quotes VALUES('136','Here be Dragons');
INSERT INTO quotes VALUES('137','Herp derp I left the debug in there and forgot to reset errors.');
INSERT INTO quotes VALUES('138','Herpderp, shoulda check if it does really compile.');
INSERT INTO quotes VALUES('139','Herping the derp');
INSERT INTO quotes VALUES('140','Herping the derp derp (silly scoping error)');
INSERT INTO quotes VALUES('141','Herping the fucking derp right here and now.');
INSERT INTO quotes VALUES('142','Herpy dooves.');
INSERT INTO quotes VALUES('143','Hide those navs, boi!');
INSERT INTO quotes VALUES('144','Hiding API key hahaha');
INSERT INTO quotes VALUES('145','I CAN HAZ COMMENTZ.');
INSERT INTO quotes VALUES('146','I CAN HAZ PYTHON, I CAN HAZ INDENTS');
INSERT INTO quotes VALUES('147','I __ a word');
INSERT INTO quotes VALUES('148','I already said I was sorry');
INSERT INTO quotes VALUES('149','I am Root. We are Root.');
INSERT INTO quotes VALUES('150','I am Spartacus');
INSERT INTO quotes VALUES('151','I am even stupider than I thought');
INSERT INTO quotes VALUES('152','I am sorry');
INSERT INTO quotes VALUES('153','I am the greatest javascript developer in the world.');
INSERT INTO quotes VALUES('154','I can''t believe it took so long to fix this.');
INSERT INTO quotes VALUES('155','I cannot believe that it took this long to write a test for this.');
INSERT INTO quotes VALUES('156','I did it for the lulz!');
INSERT INTO quotes VALUES('157','I don''t believe it');
INSERT INTO quotes VALUES('158','I don''t get paid enough for this shit.');
INSERT INTO quotes VALUES('159','I don''t give a damn ''bout my reputation');
INSERT INTO quotes VALUES('160','I don''t know what the hell I was thinking.');
INSERT INTO quotes VALUES('161','I don''t know what these changes are supposed to accomplish but somebody told me to make them.');
INSERT INTO quotes VALUES('162','I don''t know why. Just move on.');
INSERT INTO quotes VALUES('163','I dont know what I am doing');
INSERT INTO quotes VALUES('164','I expected something different.');
INSERT INTO quotes VALUES('165','I forgot to commit... So here you go.');
INSERT INTO quotes VALUES('166','I had a cup of tea and now it''s fixed');
INSERT INTO quotes VALUES('167','I hate this fucking language.');
INSERT INTO quotes VALUES('168','I have no idea what I''m doing here.');
INSERT INTO quotes VALUES('169','I honestly wish I could remember what was going on here...');
INSERT INTO quotes VALUES('170','I immediately regret this commit.');
INSERT INTO quotes VALUES('171','I just evaluated random code in my console');
INSERT INTO quotes VALUES('172','I just wanna tell you how I''m feeling');
INSERT INTO quotes VALUES('173','I know what I am doing. Trust me.');
INSERT INTO quotes VALUES('174','I know, I know, this is not how IÕm supposed to do it, but I can''t think of something better.');
INSERT INTO quotes VALUES('175','I made leetle mistake');
INSERT INTO quotes VALUES('176','I must enjoy torturing myself');
INSERT INTO quotes VALUES('177','I must have been drunk.');
INSERT INTO quotes VALUES('178','I must sleep... it''s working... in just three hours...');
INSERT INTO quotes VALUES('179','I really should''ve committed this when I finished it...');
INSERT INTO quotes VALUES('180','I should get a raise for this.');
INSERT INTO quotes VALUES('181','I should have had a V8 this morning.');
INSERT INTO quotes VALUES('182','I think now it works');
INSERT INTO quotes VALUES('183','I transformed a bug into a feature. Once you learn how, you''ll never forget it');
INSERT INTO quotes VALUES('184','I understand that it''s an antipattern, but it''s convenient.');
INSERT INTO quotes VALUES('185','I was told to leave it alone, but I have this thing called OCD, you see');
INSERT INTO quotes VALUES('186','I was wrong...');
INSERT INTO quotes VALUES('187','I will not apologize for art.');
INSERT INTO quotes VALUES('188','I will run ''terraform fmt'' before committing.');
INSERT INTO quotes VALUES('189','I would rather be playing SC2.');
INSERT INTO quotes VALUES('190','I''M PUSHING.');
INSERT INTO quotes VALUES('191','I''ll explain this when I''m sober .. or revert it');
INSERT INTO quotes VALUES('192','I''ll explain when you''re older!');
INSERT INTO quotes VALUES('193','I''ll mention this again, if you''re git-blaming this, don''t come slap me personally. This code straight ported from another project and we WILL refactor this in the future. This is a temporary solution. OK I guess you can slap me for porting this as is, but still.');
INSERT INTO quotes VALUES('194','I''m guessing this may start causing us problems either soon or never.');
INSERT INTO quotes VALUES('195','I''m human');
INSERT INTO quotes VALUES('196','I''m hungry');
INSERT INTO quotes VALUES('197','I''m just a grunt. Don''t blame me for this awful PoS.');
INSERT INTO quotes VALUES('198','I''m sorry.');
INSERT INTO quotes VALUES('199','I''m too foo for this bar');
INSERT INTO quotes VALUES('200','I''m too old for this shit!');
INSERT INTO quotes VALUES('201','I''m totally adding this to epic win. +300');
INSERT INTO quotes VALUES('202','ID:10T Error');
INSERT INTO quotes VALUES('203','IEize');
INSERT INTO quotes VALUES('204','If it''s hacky and you know it clap you hands (clap clap)!');
INSERT INTO quotes VALUES('205','If it''s stupid and it works, it ain''t stupid');
INSERT INTO quotes VALUES('206','Improvements');
INSERT INTO quotes VALUES('207','Improving the fix');
INSERT INTO quotes VALUES('208','Insert Commit Message Here');
INSERT INTO quotes VALUES('209','Inside we both know what''s been going on');
INSERT INTO quotes VALUES('210','Is there an achievement for this?');
INSERT INTO quotes VALUES('211','Is there an award for this?');
INSERT INTO quotes VALUES('212','Issue #XNUM10X is now Issue #XNUM30X');
INSERT INTO quotes VALUES('213','It Compiles! 50 Points For Gryffindor.');
INSERT INTO quotes VALUES('214','It compiles! Ship it!');
INSERT INTO quotes VALUES('215','It fucking compiles \:D/');
INSERT INTO quotes VALUES('216','It only compiles every XNUM2,5X tries... good luck.');
INSERT INTO quotes VALUES('217','It was the best of times, it was the worst of times');
INSERT INTO quotes VALUES('218','It worked for me...');
INSERT INTO quotes VALUES('219','It works on my computer');
INSERT INTO quotes VALUES('220','It works!');
INSERT INTO quotes VALUES('221','It''d be nice if type errors caused the compiler to issue a type error');
INSERT INTO quotes VALUES('222','It''s 2016; why are we using ColdFusion?!');
INSERT INTO quotes VALUES('223','It''s Working!');
INSERT INTO quotes VALUES('224','It''s getting hard to keep up with the crap I''ve trashed');
INSERT INTO quotes VALUES('225','It''s possible! you can turn a 50-line code chunk into just 3 lines. Here''s how');
INSERT INTO quotes VALUES('226','It''s secret!');
INSERT INTO quotes VALUES('227','It''s time to go home');
INSERT INTO quotes VALUES('228','Just committing so I can go home');
INSERT INTO quotes VALUES('229','Just stop reading these for a while, ok..');
INSERT INTO quotes VALUES('230','LAST time, XNAMEX, /dev/urandom IS NOT a variable name generator...');
INSERT INTO quotes VALUES('231','LOL!');
INSERT INTO quotes VALUES('232','LOTS of changes. period');
INSERT INTO quotes VALUES('233','Landed.');
INSERT INTO quotes VALUES('234','Last time I said it works? I was kidding.  Try this.');
INSERT INTO quotes VALUES('235','Locating the required gigapixels to render...');
INSERT INTO quotes VALUES('236','Lock S-foils in attack position');
INSERT INTO quotes VALUES('237','Love coding? here''s the secret reason why');
INSERT INTO quotes VALUES('238','Low On Caffeine, Please Forgive Coding Style');
INSERT INTO quotes VALUES('239','MOAR BIFURCATION');
INSERT INTO quotes VALUES('240','Made it to compile...');
INSERT INTO quotes VALUES('241','Major fixup.');
INSERT INTO quotes VALUES('242','Make Sure You Are Square With Your God Before Trying To Merge This');
INSERT INTO quotes VALUES('243','Make that it works in 90% of the cases.  3:30.');
INSERT INTO quotes VALUES('244','Merge pull my finger request');
INSERT INTO quotes VALUES('245','Merge pull request #67 from Lazersmoke/fix-andys-shit Fix andys shit');
INSERT INTO quotes VALUES('246','Merging ''WIP: Do Not Merge This Branch'' Into Master');
INSERT INTO quotes VALUES('247','Merging the merge');
INSERT INTO quotes VALUES('248','Minor updates');
INSERT INTO quotes VALUES('249','Misc. fixes');
INSERT INTO quotes VALUES('250','Mongo.db was empty, filled now with good stuff');
INSERT INTO quotes VALUES('251','More ignore');
INSERT INTO quotes VALUES('252','Moved something to somewhere... goodnight...');
INSERT INTO quotes VALUES('253','My bad');
INSERT INTO quotes VALUES('254','My boss forced me to build this feature... Pure shit.');
INSERT INTO quotes VALUES('255','NOJIRA: No cry');
INSERT INTO quotes VALUES('256','NSA backdoor - ignore');
INSERT INTO quotes VALUES('257','Never Run This Commit As Root');
INSERT INTO quotes VALUES('258','Never before had a small typo like this one caused so much damage.');
INSERT INTO quotes VALUES('259','Never gonna give you up');
INSERT INTO quotes VALUES('260','Never gonna give, never gonna give');
INSERT INTO quotes VALUES('261','Never gonna let you down');
INSERT INTO quotes VALUES('262','Never gonna make you cry');
INSERT INTO quotes VALUES('263','Never gonna run around and desert you');
INSERT INTO quotes VALUES('264','Never gonna say goodbye');
INSERT INTO quotes VALUES('265','Never gonna tell a lie and hurt you');
INSERT INTO quotes VALUES('266','Next time someone asks you how to fix an infinite loop, remember this commit');
INSERT INTO quotes VALUES('267','Nitpicking about alphabetizing methods, minor OCD thing');
INSERT INTO quotes VALUES('268','No changes after this point.');
INSERT INTO quotes VALUES('269','No changes made');
INSERT INTO quotes VALUES('270','No time to commit.. My people need me!');
INSERT INTO quotes VALUES('271','Nobody had ever created a function like this one before.');
INSERT INTO quotes VALUES('272','Not one conflict, today was a good day.');
INSERT INTO quotes VALUES('273','Not sure why');
INSERT INTO quotes VALUES('274','Nothing to see here, move along');
INSERT INTO quotes VALUES('275','Now added delete for real');
INSERT INTO quotes VALUES('276','Now it''s all microservices, I hope the fad persists.');
INSERT INTO quotes VALUES('277','Now we tell you your browser sucks in your native tongue.');
INSERT INTO quotes VALUES('278','Obligatory placeholder commit message');
INSERT INTO quotes VALUES('279','Oh my god what year is it?!');
INSERT INTO quotes VALUES('280','Oh no');
INSERT INTO quotes VALUES('281','Ok');
INSERT INTO quotes VALUES('282','Ok, 5am, it works.  For real.');
INSERT INTO quotes VALUES('283','One does not simply merge into master');
INSERT INTO quotes VALUES('284','One little whitespace gets its very own commit! Oh, life is so erratic!');
INSERT INTO quotes VALUES('285','One more time, but with feeling.');
INSERT INTO quotes VALUES('286','Only Tom Cruise knows why.');
INSERT INTO quotes VALUES('287','Out for vacation... DONT YOU DARE TO CALL ME.');
INSERT INTO quotes VALUES('288','PEBKAC');
INSERT INTO quotes VALUES('289','Peopleware Chapter 8: "You Never Get Anything Done around Here between 9 and 5."');
INSERT INTO quotes VALUES('290','Pig');
INSERT INTO quotes VALUES('291','Pipeline goes brrrrrrr');
INSERT INTO quotes VALUES('292','Please enter the commit message for your changes. Lines starting with ''#'' will be ignored, and an empty message aborts the commit.');
INSERT INTO quotes VALUES('293','Please forgive me');
INSERT INTO quotes VALUES('294','Please no changes this time.');
INSERT INTO quotes VALUES('295','Please our Lord and Savior the Great Linter.');
INSERT INTO quotes VALUES('296','Popping stash');
INSERT INTO quotes VALUES('297','Programming the flux capacitor');
INSERT INTO quotes VALUES('298','Push poorly written test can down the road another ten years');
INSERT INTO quotes VALUES('299','Put everything in its right place');
INSERT INTO quotes VALUES('300','QuickFix.');
INSERT INTO quotes VALUES('301','REALLY FUCKING FIXED');
INSERT INTO quotes VALUES('302','Refactor factories, revisit visitors');
INSERT INTO quotes VALUES('303','Refactored configuration.');
INSERT INTO quotes VALUES('304','Reinventing the wheel. Again.');
INSERT INTO quotes VALUES('305','Removed code.');
INSERT INTO quotes VALUES('306','Removed test case since code didn''t pass QA');
INSERT INTO quotes VALUES('307','Removed the 2gb .hprof file from git history');
INSERT INTO quotes VALUES('308','Removing unecessary stuff');
INSERT INTO quotes VALUES('309','Replace all whitespaces with tabs.');
INSERT INTO quotes VALUES('310','Reset error count between rows. herpderp');
INSERT INTO quotes VALUES('311','Reticulating splines...');
INSERT INTO quotes VALUES('312','Revert "fuckup".');
INSERT INTO quotes VALUES('313','Revert "git please work"');
INSERT INTO quotes VALUES('314','Revert "just testing, remember to revert"');
INSERT INTO quotes VALUES('315','Revert this commit');
INSERT INTO quotes VALUES('316','Rush B!');
INSERT INTO quotes VALUES('317','SEXY RUSSIAN CODES WAITING FOR YOU TO CALL');
INSERT INTO quotes VALUES('318','SHIT ===> GOLD');
INSERT INTO quotes VALUES('319','SOAP is a piece of shit');
INSERT INTO quotes VALUES('320','Saint Pipeline, please give me the green light');
INSERT INTO quotes VALUES('321','Same as last commit with changes');
INSERT INTO quotes VALUES('322','See last commit');
INSERT INTO quotes VALUES('323','Shit code!');
INSERT INTO quotes VALUES('324','Shovelling coal into the server...');
INSERT INTO quotes VALUES('325','So my boss wanted this button ...');
INSERT INTO quotes VALUES('326','Some bugs fixed');
INSERT INTO quotes VALUES('327','Some shit.');
INSERT INTO quotes VALUES('328','Somebody set up us the bomb.');
INSERT INTO quotes VALUES('329','Something fixed');
INSERT INTO quotes VALUES('330','Spinning up the hamster...');
INSERT INTO quotes VALUES('331','Still can''t get this right...');
INSERT INTO quotes VALUES('332','Stuff');
INSERT INTO quotes VALUES('333','Switched off unit test XNUM15X because the build had to go out now and there was no time to fix it properly.');
INSERT INTO quotes VALUES('334','TDD: 1, Me: 0');
INSERT INTO quotes VALUES('335','TODO: Fix later');
INSERT INTO quotes VALUES('336','TODO: Replace placeholder code');
INSERT INTO quotes VALUES('337','TODO: Replace stubs');
INSERT INTO quotes VALUES('338','TODO: Tell someone to implement this');
INSERT INTO quotes VALUES('339','TODO: write meaningful commit message');
INSERT INTO quotes VALUES('340','Test commit. Please ignore');
INSERT INTO quotes VALUES('341','Testing in progress ;)');
INSERT INTO quotes VALUES('342','Testing the test');
INSERT INTO quotes VALUES('343','That last commit message about silly mistakes pales in comparision to this one');
INSERT INTO quotes VALUES('344','That''s just how I roll');
INSERT INTO quotes VALUES('345','The dog is eating my code');
INSERT INTO quotes VALUES('346','The last time I tried this the monkey didn''t survive. Let''s hope it works better this time.');
INSERT INTO quotes VALUES('347','The same thing we do every night, Pinky - try to take over the world!');
INSERT INTO quotes VALUES('348','The universe is possible');
INSERT INTO quotes VALUES('349','They came from... Behind');
INSERT INTO quotes VALUES('350','Things went wrong...');
INSERT INTO quotes VALUES('351','This Is Why We Don''t Push To Production On Fridays');
INSERT INTO quotes VALUES('352','This branch is so dirty, even your mom can''t clean it.');
INSERT INTO quotes VALUES('353','This bug has driven lots of coders completely mad. You won''t believe how it ended up being fixed');
INSERT INTO quotes VALUES('354','This bunny should be killed.');
INSERT INTO quotes VALUES('355','This changes nothing, don''t look');
INSERT INTO quotes VALUES('356','This commit is a lie');
INSERT INTO quotes VALUES('357','This is a basic implementation that works.');
INSERT INTO quotes VALUES('358','This is my code. My code is amazing.');
INSERT INTO quotes VALUES('359','This is not a commit');
INSERT INTO quotes VALUES('360','This is not the commit message you are looking for');
INSERT INTO quotes VALUES('361','This is supposed to crash');
INSERT INTO quotes VALUES('362','This is the last time we let XNAMEX commit ascii porn in the comments.');
INSERT INTO quotes VALUES('363','This is where it all begins...');
INSERT INTO quotes VALUES('364','This is why git rebase is a horrible horrible thing.');
INSERT INTO quotes VALUES('365','This is why the cat shouldn''t sit on my keyboard.');
INSERT INTO quotes VALUES('366','This really should not take 19 minutes to build.');
INSERT INTO quotes VALUES('367','This should work until december 2013.');
INSERT INTO quotes VALUES('368','This solves it.');
INSERT INTO quotes VALUES('369','This was the most stupid bug in the world, fixed in the smartest way ever');
INSERT INTO quotes VALUES('370','This will definitely break in 20XNUM20,89X (TODO)');
INSERT INTO quotes VALUES('371','To be honest, I do not quite remember everything I changed here today. But it is all good, I tell ya.');
INSERT INTO quotes VALUES('372','To those I leave behind, good luck!');
INSERT INTO quotes VALUES('373','Todo!!!');
INSERT INTO quotes VALUES('374','Too lazy to write descriptive message');
INSERT INTO quotes VALUES('375','Too tired to write descriptive message');
INSERT INTO quotes VALUES('376','Transpiled mainframe.');
INSERT INTO quotes VALUES('377','Trust me, I''m an engineer!... What the f*ck did just happened here?');
INSERT INTO quotes VALUES('378','Trust me, it''s not badly written. It''s just way above your head.');
INSERT INTO quotes VALUES('379','Trying to fake a conflict');
INSERT INTO quotes VALUES('380','Ugh. Bad rebase.');
INSERT INTO quotes VALUES('381','Undoing last comming');
INSERT INTO quotes VALUES('382','Update .gitignore');
INSERT INTO quotes VALUES('383','Update commit_messages.txt');
INSERT INTO quotes VALUES('384','Updated');
INSERT INTO quotes VALUES('385','Updated build targets.');
INSERT INTO quotes VALUES('386','Updated framework to the lattest version');
INSERT INTO quotes VALUES('387','Use a real JS construct, WTF knows why this works in chromium.');
INSERT INTO quotes VALUES('388','Useful text');
INSERT INTO quotes VALUES('389','Version control is awful');
INSERT INTO quotes VALUES('390','WHO THE FUCK CAME UP WITH MAKE?');
INSERT INTO quotes VALUES('391','WIP, always');
INSERT INTO quotes VALUES('392','WIPTF');
INSERT INTO quotes VALUES('393','WTF is this.');
INSERT INTO quotes VALUES('394','We Had To Use Dark Magic To Make This Work');
INSERT INTO quotes VALUES('395','We know the game and we''re gonna play it');
INSERT INTO quotes VALUES('396','We should delete this crap before shipping.');
INSERT INTO quotes VALUES('397','We should get someone from Purdue to do this. They are the boilerplaters.');
INSERT INTO quotes VALUES('398','We''ll figure it out on Monday');
INSERT INTO quotes VALUES('399','We''re no strangers to love');
INSERT INTO quotes VALUES('400','We''ve known each other for so long');
INSERT INTO quotes VALUES('401','Well the book was obviously wrong.');
INSERT INTO quotes VALUES('402','Well, it''s doing something.');
INSERT INTO quotes VALUES('403','What happens in vegas stays in vegas');
INSERT INTO quotes VALUES('404','Whatever will be, will be 8{');
INSERT INTO quotes VALUES('405','Whatever.');
INSERT INTO quotes VALUES('406','Whee, good night.');
INSERT INTO quotes VALUES('407','Whee.');
INSERT INTO quotes VALUES('408','Who Let the Bugs Out??');
INSERT INTO quotes VALUES('409','Who has two thumbs and remembers the rudiments of his linear algebra courses?  Apparently, this guy.');
INSERT INTO quotes VALUES('410','Who knows WTF?!');
INSERT INTO quotes VALUES('411','Who knows...');
INSERT INTO quotes VALUES('412','Why The Fuck?');
INSERT INTO quotes VALUES('413','Working on WIP');
INSERT INTO quotes VALUES('414','Working on tests (haha)');
INSERT INTO quotes VALUES('415','Wubbalubbadubdub!');
INSERT INTO quotes VALUES('416','XNAMEX broke the regex, lame');
INSERT INTO quotes VALUES('417','XNAMEX made me do it');
INSERT INTO quotes VALUES('418','XNAMEX rebase plx?');
INSERT INTO quotes VALUES('419','XNAMEX sucks');
INSERT INTO quotes VALUES('420','XUPPERNAMEX SUCKS');
INSERT INTO quotes VALUES('421','XUPPERNAMEX, WE WENT OVER THIS. C++ IO SUCKS.');
INSERT INTO quotes VALUES('422','XUPPERNAMEX, WE WENT OVER THIS. EXPANDTAB.');
INSERT INTO quotes VALUES('423','Yep, XNAMEX was right on this one.');
INSERT INTO quotes VALUES('424','Yes, I was being sarcastic.');
INSERT INTO quotes VALUES('425','You can''t see it, but I''m making a very angry face right now');
INSERT INTO quotes VALUES('426','You know the rules and so do I');
INSERT INTO quotes VALUES('427','You should have trusted me.');
INSERT INTO quotes VALUES('428','You wouldn''t get this from any other guy');
INSERT INTO quotes VALUES('429','Your commit is writing checks your merge can''t cash.');
INSERT INTO quotes VALUES('430','Your heart''s been aching but you''re too shy to say it');
INSERT INTO quotes VALUES('431','[Insert your commit message here. Be sure to make it descriptive.]');
INSERT INTO quotes VALUES('432','[no message]');
INSERT INTO quotes VALUES('433','[skip ci] I''ll fix the build monday');
INSERT INTO quotes VALUES('434','_');
INSERT INTO quotes VALUES('435','a few bits tried to escape, but we caught them');
INSERT INTO quotes VALUES('436','a lot of shit');
INSERT INTO quotes VALUES('437','accidental commit');
INSERT INTO quotes VALUES('438','add actual words');
INSERT INTO quotes VALUES('439','add dirty scripts from the dark side of the universe');
INSERT INTO quotes VALUES('440','added code');
INSERT INTO quotes VALUES('441','added message');
INSERT INTO quotes VALUES('442','added security.');
INSERT INTO quotes VALUES('443','added some filthy stuff');
INSERT INTO quotes VALUES('444','added super-widget 2.0.');
INSERT INTO quotes VALUES('445','after of this commit remember do a git reset hard');
INSERT INTO quotes VALUES('446','ajax-loader hotness, oh yeah');
INSERT INTO quotes VALUES('447','and a comma');
INSERT INTO quotes VALUES('448','and so the crazy refactoring process sees the sunlight after some months in the dark!');
INSERT INTO quotes VALUES('449','another big bag of changes');
INSERT INTO quotes VALUES('450','apparently i did somethingÉ');
INSERT INTO quotes VALUES('451','arrgghh... damn this thing for not working.');
INSERT INTO quotes VALUES('452','arrrggghhhhh fixed!');
INSERT INTO quotes VALUES('453','asdfasdfasdfasdfasdfasdfadsf');
INSERT INTO quotes VALUES('454','assorted changes');
INSERT INTO quotes VALUES('455','bad things happen when you forget about that one little change you made ages ago');
INSERT INTO quotes VALUES('456','bara bra grejjor');
INSERT INTO quotes VALUES('457','better code');
INSERT INTO quotes VALUES('458','better grepping');
INSERT INTO quotes VALUES('459','better ignores');
INSERT INTO quotes VALUES('460','betterer code');
INSERT INTO quotes VALUES('461','bifurcation');
INSERT INTO quotes VALUES('462','bla');
INSERT INTO quotes VALUES('463','breathe, =, breathe');
INSERT INTO quotes VALUES('464','buenas those-things.');
INSERT INTO quotes VALUES('465','bug fix');
INSERT INTO quotes VALUES('466','bugger');
INSERT INTO quotes VALUES('467','bump to 0.0.3-dev:wq');
INSERT INTO quotes VALUES('468','bumping poms');
INSERT INTO quotes VALUES('469','c&p fail');
INSERT INTO quotes VALUES('470','changed things...');
INSERT INTO quotes VALUES('471','changes');
INSERT INTO quotes VALUES('472','ci test');
INSERT INTO quotes VALUES('473','clarify further the brokenness of C++. why the fuck are we using C++?');
INSERT INTO quotes VALUES('474','commented out failing tests');
INSERT INTO quotes VALUES('475','commit');
INSERT INTO quotes VALUES('476','copy and paste is not a design pattern');
INSERT INTO quotes VALUES('477','de-misunderestimating');
INSERT INTO quotes VALUES('478','debug line test');
INSERT INTO quotes VALUES('479','debug suff');
INSERT INTO quotes VALUES('480','debugo');
INSERT INTO quotes VALUES('481','derp, helper method rename');
INSERT INTO quotes VALUES('482','derpherp');
INSERT INTO quotes VALUES('483','diaaaaaazeeeeeeeeeepam');
INSERT INTO quotes VALUES('484','did everything');
INSERT INTO quotes VALUES('485','dirty hack, have a better idea ?');
INSERT INTO quotes VALUES('486','does it work? maybe. will I check? no.');
INSERT INTO quotes VALUES('487','doh.');
INSERT INTO quotes VALUES('488','done. going to bed now.');
INSERT INTO quotes VALUES('489','dope');
INSERT INTO quotes VALUES('490','download half the damn internet to parse a pdf');
INSERT INTO quotes VALUES('491','enabled ultra instinct');
INSERT INTO quotes VALUES('492','epic');
INSERT INTO quotes VALUES('493','eppic fail XNAMEX');
INSERT INTO quotes VALUES('494','extra debug for stuff module');
INSERT INTO quotes VALUES('495','f');
INSERT INTO quotes VALUES('496','fail');
INSERT INTO quotes VALUES('497','features');
INSERT INTO quotes VALUES('498','ffs');
INSERT INTO quotes VALUES('499','final commit.');
INSERT INTO quotes VALUES('500','first blush');
INSERT INTO quotes VALUES('501','fix');
INSERT INTO quotes VALUES('502','fix /sigh');
INSERT INTO quotes VALUES('503','fix bug, for realz');
INSERT INTO quotes VALUES('504','fix some fucking errors');
INSERT INTO quotes VALUES('505','fix tpyo');
INSERT INTO quotes VALUES('506','fixed conflicts (LOL merge -s ours; push -f)');
INSERT INTO quotes VALUES('507','fixed errors in the previous commit');
INSERT INTO quotes VALUES('508','fixed mistaken bug');
INSERT INTO quotes VALUES('509','fixed shit that havent been fixed in last commit');
INSERT INTO quotes VALUES('510','fixed some minor stuff, might need some additional work.');
INSERT INTO quotes VALUES('511','fix that damn sign!!!');
INSERT INTO quotes VALUES('512','fixed the israeli-palestinian conflict');
INSERT INTO quotes VALUES('513','fixes');
INSERT INTO quotes VALUES('514','fixing project shit');
INSERT INTO quotes VALUES('515','foo');
INSERT INTO quotes VALUES('516','forgot a contact page woops haha');
INSERT INTO quotes VALUES('517','forgot to save that file');
INSERT INTO quotes VALUES('518','forgot we''re not using a smart language');
INSERT INTO quotes VALUES('519','formatted all');
INSERT INTO quotes VALUES('520','freemasonry');
INSERT INTO quotes VALUES('521','fuckup.');
INSERT INTO quotes VALUES('522','gave up and used tables.');
INSERT INTO quotes VALUES('523','giggle.');
INSERT INTO quotes VALUES('524','git + ipynb = :(');
INSERT INTO quotes VALUES('525','git please work');
INSERT INTO quotes VALUES('526','git stash *');
INSERT INTO quotes VALUES('527','god help us all');
INSERT INTO quotes VALUES('528','grmbl');
INSERT INTO quotes VALUES('529','grrrr');
INSERT INTO quotes VALUES('530','hacky sack');
INSERT INTO quotes VALUES('531','haha yes it works now');
INSERT INTO quotes VALUES('532','happy monday _ bleh _');
INSERT INTO quotes VALUES('533','harharhar');
INSERT INTO quotes VALUES('534','he knows.');
INSERT INTO quotes VALUES('535','herpderp');
INSERT INTO quotes VALUES('536','herpderp (redux)');
INSERT INTO quotes VALUES('537','hey, look over there!');
INSERT INTO quotes VALUES('538','hey, what''s that over there?!');
INSERT INTO quotes VALUES('539','hmmm');
INSERT INTO quotes VALUES('540','holy shit it''s functional');
INSERT INTO quotes VALUES('541','hoo boy');
INSERT INTO quotes VALUES('542','hopefully going to get a successful build got damn it');
INSERT INTO quotes VALUES('543','i dunno, maybe this works');
INSERT INTO quotes VALUES('544','i hid an easter egg in the code. can you find it?');
INSERT INTO quotes VALUES('545','i need therapy');
INSERT INTO quotes VALUES('546','i think i fixed a bug...');
INSERT INTO quotes VALUES('547','if you''re not using et, fuck off');
INSERT INTO quotes VALUES('548','implemented missing semicolon');
INSERT INTO quotes VALUES('549','improved function');
INSERT INTO quotes VALUES('550','include shit');
INSERT INTO quotes VALUES('551','increased loading time by a bit');
INSERT INTO quotes VALUES('552','it is hump day _^_');
INSERT INTO quotes VALUES('553','it''s friday');
INSERT INTO quotes VALUES('554','jobs... steve jobs');
INSERT INTO quotes VALUES('555','just checking if git is working properly...');
INSERT INTO quotes VALUES('556','just shoot me');
INSERT INTO quotes VALUES('557','just trolling the repo');
INSERT INTO quotes VALUES('558','last hope failed, maybe now');
INSERT INTO quotes VALUES('559','last minute fixes.');
INSERT INTO quotes VALUES('560','less french words');
INSERT INTO quotes VALUES('561','lets drink beer');
INSERT INTO quotes VALUES('562','lol');
INSERT INTO quotes VALUES('563','lol digg');
INSERT INTO quotes VALUES('564','lolwhat?');
INSERT INTO quotes VALUES('565','lots and lots of changes');
INSERT INTO quotes VALUES('566','lots of changes after a lot of time');
INSERT INTO quotes VALUES('567','magic, have no clue but it works');
INSERT INTO quotes VALUES('568','making code less cancer');
INSERT INTO quotes VALUES('569','making this thing actually usable.');
INSERT INTO quotes VALUES('570','marks');
INSERT INTO quotes VALUES('571','mergeconflix is the new hottest Gaul on the block');
INSERT INTO quotes VALUES('572','mergederp');
INSERT INTO quotes VALUES('573','minor changes');
INSERT INTO quotes VALUES('574','more debug... who overwrote!');
INSERT INTO quotes VALUES('575','more fixes');
INSERT INTO quotes VALUES('576','more ignored words');
INSERT INTO quotes VALUES('577','more ignores');
INSERT INTO quotes VALUES('578','more stuff');
INSERT INTO quotes VALUES('579','move your body every every body');
INSERT INTO quotes VALUES('580','need another beer');
INSERT INTO quotes VALUES('581','needs more cow bell');
INSERT INTO quotes VALUES('582','omg what have I done?');
INSERT INTO quotes VALUES('583','omgsosorry');
INSERT INTO quotes VALUES('584','oops');
INSERT INTO quotes VALUES('585','oops - thought I got that one.');
INSERT INTO quotes VALUES('586','oops!');
INSERT INTO quotes VALUES('587','oops, forgot to add the file');
INSERT INTO quotes VALUES('588','oopsie B|');
INSERT INTO quotes VALUES('589','pam anderson is going to love me.');
INSERT INTO quotes VALUES('590','pay no attention to the man behind the curtain');
INSERT INTO quotes VALUES('591','pep8 - cause I fell like doing a barrel roll');
INSERT INTO quotes VALUES('592','pep8 fixer');
INSERT INTO quotes VALUES('593','perfect...');
INSERT INTO quotes VALUES('594','permanent hack, do not revert');
INSERT INTO quotes VALUES('595','pgsql is being a pain');
INSERT INTO quotes VALUES('596','pgsql is more strict, increase the hackiness up to 11');
INSERT INTO quotes VALUES('597','pointless limitation');
INSERT INTO quotes VALUES('598','pr is failing but merging anyways, because I am an admin');
INSERT INTO quotes VALUES('599','project lead is allergic to changes...');
INSERT INTO quotes VALUES('600','put code that worked where the code that didn''t used to be');
INSERT INTO quotes VALUES('601','rats');
INSERT INTO quotes VALUES('602','really ignore ignored worsd');
INSERT INTO quotes VALUES('603','refuckulated the carbonator');
INSERT INTO quotes VALUES('604','remove certain things and added stuff');
INSERT INTO quotes VALUES('605','remove debug<br/>all good');
INSERT INTO quotes VALUES('606','removed echo and die statements, lolz.');
INSERT INTO quotes VALUES('607','removed tests since i can''t make them green');
INSERT INTO quotes VALUES('608','removing unit tests');
INSERT INTO quotes VALUES('609','restored deleted entities just to be sure');
INSERT INTO quotes VALUES('610','s/    /  /g');
INSERT INTO quotes VALUES('611','s/import/include/');
INSERT INTO quotes VALUES('612','should get thru ci now');
INSERT INTO quotes VALUES('613','should work I guess...');
INSERT INTO quotes VALUES('614','should work now.');
INSERT INTO quotes VALUES('615','small is a real HTML tag, who knew.');
INSERT INTO quotes VALUES('616','some brief changes');
INSERT INTO quotes VALUES('617','some stuff working haha');
INSERT INTO quotes VALUES('618','somebody keeps erasing my changes.');
INSERT INTO quotes VALUES('619','someday I gonna kill someone for this shit...');
INSERT INTO quotes VALUES('620','someone fails and it isn''t me');
INSERT INTO quotes VALUES('621','sometimes you just herp the derp so hard it herpderps');
INSERT INTO quotes VALUES('622','speling is difikult');
INSERT INTO quotes VALUES('623','squash me');
INSERT INTO quotes VALUES('624','starting the service is always better');
INSERT INTO quotes VALUES('625','still trying to render a damn cube');
INSERT INTO quotes VALUES('626','stopped caring XNUM8,23X commits ago');
INSERT INTO quotes VALUES('627','stuff');
INSERT INTO quotes VALUES('628','syntax');
INSERT INTO quotes VALUES('629','tagging release w.t.f.');
INSERT INTO quotes VALUES('630','that coulda been bad');
INSERT INTO quotes VALUES('631','that''s all folks');
INSERT INTO quotes VALUES('632','the magic is real');
INSERT INTO quotes VALUES('633','these confounded tests drive me nuts');
INSERT INTO quotes VALUES('634','these guys are flipped');
INSERT INTO quotes VALUES('635','things occurred');
INSERT INTO quotes VALUES('636','third time''s a charm');
INSERT INTO quotes VALUES('637','this doesn''t really make things faster, but I tried');
INSERT INTO quotes VALUES('638','this is Spartaaaaaaaa');
INSERT INTO quotes VALUES('639','this is how we generate our shit.');
INSERT INTO quotes VALUES('640','this is my quickfix branch and i will use to do my quickfixes');
INSERT INTO quotes VALUES('641','this is why docs are important');
INSERT INTO quotes VALUES('642','this should fix it');
INSERT INTO quotes VALUES('643','tl;dr');
INSERT INTO quotes VALUES('644','totally more readable');
INSERT INTO quotes VALUES('645','touched...');
INSERT INTO quotes VALUES('646','try our sister game minceraft!');
INSERT INTO quotes VALUES('647','trying to do something right!');
INSERT INTO quotes VALUES('648','tunning');
INSERT INTO quotes VALUES('649','typo');
INSERT INTO quotes VALUES('650','uhhhhhh');
INSERT INTO quotes VALUES('651','unh');
INSERT INTO quotes VALUES('652','unionfind is no longer being molested.');
INSERT INTO quotes VALUES('653','various changes');
INSERT INTO quotes VALUES('654','well crap.');
INSERT INTO quotes VALUES('655','what the hell happened here');
INSERT INTO quotes VALUES('656','what is estonia up to now ...');
INSERT INTO quotes VALUES('657','whatthecommit.comÕs server IP address could not be found.');
INSERT INTO quotes VALUES('658','who has two thumbs and is a genius? not this guy!');
INSERT INTO quotes VALUES('659','who hurt you');
INSERT INTO quotes VALUES('660','whooooooooooooooooooooooooooo');
INSERT INTO quotes VALUES('661','why is everything broken');
INSERT INTO quotes VALUES('662','wip');
INSERT INTO quotes VALUES('663','woa!! this one was really HARD!');
INSERT INTO quotes VALUES('664','work in progress');
INSERT INTO quotes VALUES('665','workaround for ant being a pile of fail');
INSERT INTO quotes VALUES('666','wrapping should work properly. Probably.');
INSERT INTO quotes VALUES('667','yet another quality commit');
INSERT INTO quotes VALUES('668','yo recipes');
INSERT INTO quotes VALUES('669','yolo push');
INSERT INTO quotes VALUES('670','you do wanna make me cry and i wanna say goodbye');

