name = "test"
compatibility_date = "2023-12-01"

# [vars]
# MY_VAR = "my-variable"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# TODO: Update or remove this once SST has implemented D1 full support

[[d1_databases]]
binding = "DB"
database_name = "timmoc-cody-timmocdbdatabase"
database_id = "89361f7b-d98e-4740-887f-624f62696a0f"
# TODO: remove the migrations dir
migrations_dir = "migrations"
# [ai]
# binding = "AI"
