name = "test"
compatibility_date = "2023-12-01"

# [vars]
# MY_VAR = "my-variable"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# TODO: Update or remove this once SST has implemented D1 full support

[[d1_databases]]
binding = "DB"
# database_name = "timmoc-cody-timmocdbdatabase"
# database_id = "fb7ed53e-a9d8-430a-97f3-bc5fe5cd1f34"
database_name = "timmoc-production-timmocdbdatabase"
database_id = "e4712260-6ab1-4652-83b0-29bc858b35fb"
# TODO: remove the migrations dir
migrations_dir = "migrations"
# [ai]
# binding = "AI"
