name: Delete PR previews in Development

on:
  pull_request:
    types:
      - closed
  workflow_dispatch:
    inputs:
      stage_name:
        description: "Stage name to remove"
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: "Remove stage pr${{ github.event.pull_request.number || github.event.inputs.stage_name }} in Development"
    permissions:
      id-token: write
      contents: read
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}

    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Install SST
        run: curl -fsSL https://ion.sst.dev/install | bash

      - name: Remove pr${{ github.event.pull_request.number || github.event.inputs.stage_name }} from Cloudflare
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          NO_BUN: true
        run: |
          sst remove --stage=pr${{ github.event.pull_request.number || github.event.inputs.stage_name }} --verbose
