name: Delete PR previews in Development

on:
  pull_request:
    types:
      - closed
  workflow_dispatch:
    inputs:
      stage_name:
        description: "Stage Name (or PR number)"
        required: true
jobs:
  deploy:
    runs-on: ubuntu-latest
    name: "Remove pr-${{ github.event.pull_request.number || github.event.inputs.stage_name }} in Development"
    permissions:
      id-token: write
      contents: read
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}

    steps:
      - uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v4
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::528914924198:role/GitHubAction-AssumeRoleWithAction
          aws-region: us-east-2

      - name: Remove stage pr-${{ github.event.pull_request.number || github.event.inputs.stage_name }} from AWS Development
        run: |
          pnpm sst remove --stage pr-${{ github.event.pull_request.number || github.event.inputs.stage_name }}
