name: Deploy PR previews to Development

on:
  #push:
  #brnches:
  #- "!main"
  pull_request:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: arc-runner-set-timmoc
    name: "Build and Deploy pr-${{ github.event.pull_request.number }} to Development"
    permissions:
      id-token: write
      contents: read
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}

    steps:
      - uses: actions/checkout@v4

      - name: Install Bun dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - uses: actions/cache@v4
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-${{ matrix.bun }}-bun-${{ hashFiles('**/bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.bun }}-bun-

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::331093400597:role/AWS-Credentials-for-GitHub-Actions-Role-Role-qmUnm5NVyP1n
          aws-region: us-east-2

      - name: Deploy pr-${{ github.event.pull_request.number }} to AWS Development
        run: |
          bun sst deploy --stage pr-${{ github.event.pull_request.number }}

      - name: Retreive Deployment URL
        id: extract-url
        run: |
          echo "URL=$(jq -r '..? | .URL | select( . != null )' .sst/outputs.json)" >> $GITHUB_OUTPUT
