name: Deploy to Prod

on:
  push:
    branches:
      - main
  # pull_request:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: "Deploy to Prod"
    permissions:
      id-token: write
      contents: read
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}

    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Install SST
        run: curl -fsSL https://ion.sst.dev/install | bash

      - name: Deploy Prod to Cloudflare
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          NO_BUN: true
        run: |
          sst deploy --stage=prod --verbose

      - name: Retreive Deployment URL
        id: extract-url
        run: |
          echo "URL=$(jq -r '..? | .URL | select( . != null )' .sst/outputs.json)" >> $GITHUB_OUTPUT
