name: Deploy to Prod

on:
  push:
    branches:
      - main
  # pull_request:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: arc-runner-set-timmoc
    name: "Build and Deploy to Prod"
    permissions:
      id-token: write
      contents: read
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}

    steps:
      - uses: actions/checkout@v4

      - name: Install Bun dependencies
        run: apt list --installed

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - uses: actions/cache@v4
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-${{ matrix.bun }}-bun-${{ hashFiles('**/bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.bun }}-bun-

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::331093400597:role/GitHubAction-AssumeRoleWithAction
          aws-region: us-east-2

      - name: Deploy to Prod
        run: |
          bun sst deploy --stage prod

      - name: Retreive Deployment URL
        id: extract-url
        run: |
          echo "URL=$(jq -r '..? | .URL | select( . != null )' .sst/outputs.json)" >> $GITHUB_OUTPUT
