name: Deploy PR previews to Development

on:
  #push:
  #brnches:
  #- "!main"
  pull_request:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: "Build and Deploy ${{ github.event.pull_request.number }} to Development"
    permissions:
      id-token: write
      contents: read
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}

    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Install SST
        run: curl -fsSL https://ion.sst.dev/install | bash

      - name: Deploy pr${{ github.event.pull_request.number }} to Cloudflare
        env: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        run: |
          sst deploy --stage=pr${{ github.event.pull_request.number }} --verbose
