name: Deploy PR previews to Development

on:
  #push:
  #brnches:
  #- "!main"
  pull_request:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: "Build and Deploy ${{ github.event.pull_request.number }} to Development"
    permissions:
      id-token: write
      contents: read
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}

    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - uses: actions/setup-go@v5
        with:
          go-version: "stable"

      - name: Install dependencies
        run: bun install

      - name: Install SST
        run: curl -fsSL https://ion.sst.dev/install | bash

      - name: Deploy pr-${{ github.event.pull_request.number }} to Cloudflare
        run: |
          sst deploy --stage=pr${{ github.event.pull_request.number }} --verbose

      # - name: Retreive Deployment URL
      #   id: extract-url
      #   run: |
      #     echo "URL=$(jq -r '..? | .URL | select( . != null )' .sst/outputs.json)" >> $GITHUB_OUTPUT
